### ISSUE TITLE
suggestion - separate out pinterest and other legit sites

### ISSUE THREAD

**Issue by nicoleahmed** [BitesizedLion/various-lists#1]
Hey great lists
Can I suggest that you separate out the legit pinterest sites and leave the clones in your general list

There are also some other sites which look quite legit (e.g. geeksforgeeks) which it might be worth separating into your personal list too? 

Would love to subscribe to your general list but don't want to block legitimate pinterest sites

**Comment by BitesizedLion** [comment]
Hi, I've separate out the "pinboards" sites (aka pinterest, flipboard) into their own list.

As for geeksforgeeks, I have moved that into my personal list.

And of course the general list is subjective so I can't guarantee the other sites are, in everyone's opinion, spam, etc. so you can always fork the repository and do your own changes if you want to.

**Comment by nicoleahmed** [comment]
hi i mentioned your list in my [big list of subscriptions](https://github.com/nicoleahmed/nicoles-ublacklist/blob/main/README.md) if you're not happy with that let me know. I've put up a disclaimer about use at own risk
